engines:
  rubocop:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: false
  duplication:
  	enabled: true
    config:
    	languages:
        javascript
exclude_paths:
  app/tests/**/*
  "**/public/**/*"